kind: pipeline
type: docker
name: default

steps:
- name: init
  image: alpine
  commands:
  - echo git clone

- name: analysis
  image: node:12.10.0
  commands:
  - echo analysis

- name: compile
  image: node:12.10.0
  commands:
  - echo yarn
  - echo yarn build

- name: build
  image: node:12.10.0
  commands:
  - echo docker build

